In [1]:
import torch
from torchvision import datasets, transforms
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from sklearn.metrics import accuracy_score

##### Downloading CIFAR 10 Dataset

In [2]:
 transform = transforms.Compose([transforms.Resize((32,32)),
                               transforms.ToTensor(),
                               transforms.Normalize((0.5, 0.5, 0.5), (0.5, 0.5, 0.5))
                               ])
train_set = datasets.CIFAR10(root='./data', train=True, download=True, transform=transform) # Data augmentation is only 
                                                                                            #done on training images
test_set = datasets.CIFAR10(root='./data', train=False, download=True, transform=transform)

Files already downloaded and verified
Files already downloaded and verified


In [3]:
classes = ('plane', 'car', 'bird', 'cat', 'deer', 'dog', 'frog', 'horse', 'ship', 'truck')

##### Taking two classes from dataset (plane, car)

In [7]:
# Taking two classses from trainset
train_set_x = []
for images, labels in train_set:
    if (labels == 0) or (labels == 1):
        train_set_x.append(images)


In [8]:
print(len(train_set_x))
print(type(train_set_x))
print(type(train_set_x[0]))
print(train_set_x[0].shape)
train_set_x[2]

10000
<class 'list'>
<class 'torch.Tensor'>
torch.Size([3, 32, 32])


tensor([[[0.5843, 0.5843, 0.6000,  ..., 0.6235, 0.6078, 0.5922],
         [0.6157, 0.6157, 0.6235,  ..., 0.6471, 0.6314, 0.6157],
         [0.6471, 0.6549, 0.6627,  ..., 0.6784, 0.6627, 0.6471],
         ...,
         [0.7098, 0.6471, 0.5216,  ..., 0.9059, 0.9137, 0.9059],
         [0.7176, 0.7020, 0.6941,  ..., 0.8902, 0.8902, 0.8902],
         [0.7020, 0.6941, 0.7020,  ..., 0.8745, 0.8745, 0.8824]],

        [[0.6000, 0.6000, 0.6157,  ..., 0.6314, 0.6157, 0.6000],
         [0.6314, 0.6314, 0.6392,  ..., 0.6549, 0.6392, 0.6235],
         [0.6627, 0.6706, 0.6784,  ..., 0.6784, 0.6706, 0.6549],
         ...,
         [0.7020, 0.6392, 0.5216,  ..., 0.8980, 0.8980, 0.9059],
         [0.7098, 0.6941, 0.6941,  ..., 0.8824, 0.8824, 0.8824],
         [0.6941, 0.6863, 0.6941,  ..., 0.8667, 0.8667, 0.8667]],

        [[0.5608, 0.5608, 0.5765,  ..., 0.5686, 0.5608, 0.5529],
         [0.5922, 0.5922, 0.6000,  ..., 0.6078, 0.5922, 0.5765],
         [0.6235, 0.6314, 0.6471,  ..., 0.6471, 0.6314, 0.

In [9]:
test_set_x = []
for images, labels in test_set:
    if(labels == 0) or (labels == 1):
        test_set_x.append(images)

In [10]:
print(len(test_set_x))
print(type(test_set_x))
print(type(test_set_x[0]))
print(test_set_x[0].shape)
print(test_set_x[0])

2000
<class 'list'>
<class 'torch.Tensor'>
torch.Size([3, 32, 32])
tensor([[[ 0.2157,  0.3098,  0.3804,  ...,  0.5765,  0.5843,  0.5059],
         [ 0.2000,  0.2784,  0.3412,  ...,  0.5843,  0.5922,  0.4824],
         [ 0.2157,  0.2549,  0.3176,  ...,  0.6157,  0.6000,  0.4824],
         ...,
         [-0.3020, -0.5529, -0.5216,  ..., -0.3020, -0.5373, -0.4745],
         [-0.3020, -0.5294, -0.5059,  ..., -0.5529, -0.5216, -0.4118],
         [-0.2784, -0.5294, -0.5216,  ..., -0.5294, -0.4980, -0.4275]],

        [[ 0.2235,  0.3804,  0.4039,  ...,  0.5373,  0.5843,  0.4353],
         [ 0.2157,  0.4039,  0.4431,  ...,  0.6314,  0.6863,  0.4902],
         [ 0.2078,  0.3961,  0.4510,  ...,  0.6314,  0.6863,  0.4980],
         ...,
         [-0.3804, -0.5843, -0.5216,  ..., -0.0667, -0.3804, -0.4196],
         [-0.3569, -0.5451, -0.4824,  ..., -0.4824, -0.4980, -0.4588],
         [-0.3882, -0.5922, -0.5451,  ..., -0.5059, -0.4902, -0.4667]],

        [[ 0.1686,  0.4667,  0.5137,  ...,  0.639

In [11]:
# Taking 2 classes label(true value) from trainset 
train_set_y = []
for images, labels in train_set:
    if(labels == 0) or (labels == 1):
        train_set_y.append(np.array([labels]))

In [12]:
print(len(train_set_y))
print(type(train_set_y))
print(type(train_set_y[0]))
print(train_set_y[0].shape)
#print(type(train_set_y[0])
print(train_set_y[1])

10000
<class 'list'>
<class 'numpy.ndarray'>
(1,)
[1]


In [13]:
# Taking 2 classes label(true value) from test set 
test_set_y = []
for images, labels in test_set:
    if(labels == 0) or (labels == 1):
        test_set_y.append(np.array([labels]))

In [14]:
print(len(test_set_y))
print(type(test_set_y))
print(type(test_set_y[0]))
print(test_set_y[0].shape)
print(test_set_y[1])

2000
<class 'list'>
<class 'numpy.ndarray'>
(1,)
[1]


In [15]:
#Printing lengths of trainset and test set
print("Train Example: ", len(train_set_x))
print("Test Example: ", len(test_set_x))
print("Train labels: ", len(train_set_y))
print("Test labels: ", len(test_set_y))

Train Example:  10000
Test Example:  2000
Train labels:  10000
Test labels:  2000


In [17]:
for i in range(10):
    print(test_set_y[i])

[0]
[1]
[1]
[0]
[0]
[0]
[1]
[0]
[0]
[1]


##### Reshape train and test set to row vectors

In [18]:
#For train data 
train_X = torch.stack(train_set_x, dim = 0)  #list to torch 
print(len(train_X))
print(type(train_X))

#Converting to numpy and reshaping
train_X = train_X.numpy()                 # torch to numpy 
train_X = train_X.reshape(10000, 3*32*32) # reshape to 10000 * 3072
print("\nAfter converting numpy and reshape: \n")
print(len(train_X))
print(type(train_X))
print(train_X.shape)
print(train_X[0].shape)

10000
<class 'torch.Tensor'>

After converting numpy and reshape: 

10000
<class 'numpy.ndarray'>
(10000, 3072)
(3072,)


In [19]:
#Reading one of image from train set
print(train_X[1])
print(train_X.shape[0], train_X.shape[1])
train_X[1].shape

[ 0.24705887  0.17647064  0.20000005 ... -0.8901961  -0.8666667
 -0.8509804 ]
10000 3072


(3072,)

In [20]:
# For test data 
test_X = torch.stack(test_set_x, dim = 0)
print(len(test_X))
print(type(test_X))

#Converting to numpy and reshaping 
test_X = test_X.numpy()
test_X = test_X.reshape(2000, 3*32*32)
print("\nAfter converting numpy and reshape: \n")
print(len(test_X))
print(type(test_X))
print(test_X.shape)
print(test_X[0].shape)

2000
<class 'torch.Tensor'>

After converting numpy and reshape: 

2000
<class 'numpy.ndarray'>
(2000, 3072)
(3072,)


In [21]:
print(type(train_set_y))

<class 'list'>


In [22]:
test_X[1]

array([ 0.254902  ,  0.45098042,  0.6392157 , ..., -0.75686276,
       -0.73333335, -0.78039217], dtype=float32)

In [23]:
#Converting train and test labels to numpy

#train label
train_Y = torch.FloatTensor(train_set_y)
train_Y = np.array(train_Y) #list to numpy array
print(len(train_Y))
print(type(train_Y))
print(train_Y[0])

#test label
test_Y = torch.FloatTensor(test_set_y)
test_Y = np.array(test_set_y)
print(type(test_Y))
print(test_Y[0])

10000
<class 'numpy.ndarray'>
[1.]
<class 'numpy.ndarray'>
[0]


In [24]:
print(test_Y)
test_Y.shape

[[0]
 [1]
 [1]
 ...
 [0]
 [0]
 [1]]


(2000, 1)

In [25]:
print(len(train_Y))

10000


In [27]:
train_Y[0]

array([1.], dtype=float32)

##### Building two layer Neural network with hidden layer

In [28]:
#Defining sigmoid function and derivative of sigmoid function

def sigmoid(x):
    return 1/(1 + np.exp(-x))

def sigmoid_der(x):
    return sigmoid(x) * (1 - sigmoid(x))

In [29]:
wh = np.random.rand(len(train_X[0]),1000)          # hidden layer's weight
wo = np.random.rand(1000, 1)                       # output layer's weight
lr = 0.5
print("Wh initial: ", wh)
print("\nWo initial: ", wo)

#### Training neural network for 10 epochs

for epoch in range(10):
    # feedforward
    zh = np.dot(train_X, wh)
    ah = sigmoid(zh)

    zo = np.dot(ah, wo)
    ao = sigmoid(zo)

    # Phase1 =======================

    error_out = ((1 / 2) * (np.power((ao - train_Y), 2)))
    print(error_out.sum())

    dcost_dao = ao - train_Y
    dao_dzo = sigmoid_der(zo) 
    dzo_dwo = ah

    dcost_wo = np.dot(dzo_dwo.T, dcost_dao * dao_dzo)

    # Phase 2 =======================

    # dcost_w1 = dcost_dah * dah_dzh * dzh_dw1
    # dcost_dah = dcost_dzo * dzo_dah
    dcost_dzo = dcost_dao * dao_dzo
    dzo_dah = wo
    dcost_dah = np.dot(dcost_dzo , dzo_dah.T)
    dah_dzh = sigmoid_der(zh) 
    dzh_dwh = train_X
    dcost_wh = np.dot(dzh_dwh.T, dah_dzh * dcost_dah)

    # Update Weights ================

    wh -= lr * dcost_wh
    wo -= lr * dcost_wo


Wh initial:  [[0.69730374 0.87510862 0.41308011 ... 0.84585821 0.79889732 0.46466038]
 [0.6734036  0.08356859 0.34533676 ... 0.50221798 0.60499049 0.09822113]
 [0.85871815 0.88361124 0.78443185 ... 0.91998202 0.34269728 0.75544103]
 ...
 [0.88334333 0.39587101 0.19133278 ... 0.81176991 0.59151496 0.28798863]
 [0.56825492 0.99804833 0.88802355 ... 0.85982366 0.09687269 0.45414593]
 [0.24622236 0.15162583 0.50592642 ... 0.66597909 0.06794148 0.3402268 ]]

Wo initial:  [[6.45924355e-01]
 [7.00585247e-03]
 [1.52139072e-01]
 [5.70788446e-01]
 [3.92965004e-01]
 [5.47224117e-01]
 [1.72145638e-01]
 [4.16656539e-01]
 [3.66726087e-01]
 [6.25482495e-01]
 [3.92009631e-01]
 [3.48954607e-01]
 [3.33283576e-01]
 [6.96217023e-01]
 [7.65286175e-01]
 [5.44871747e-01]
 [6.48610259e-01]
 [7.13296512e-02]
 [7.67382379e-02]
 [4.05331691e-01]
 [7.96945950e-01]
 [8.72049247e-01]
 [7.25175928e-01]
 [5.53773293e-01]
 [3.95421496e-01]
 [4.59832415e-01]
 [5.82141084e-01]
 [2.43296455e-01]
 [5.86484685e-01]
 [4.232

<ipython-input-28-34802458da0f>:4: RuntimeWarning: overflow encountered in exp
  return 1/(1 + np.exp(-x))


2320.892675702556
2316.865647501438
2315.1117154017566
2313.952690579519
2313.0334872237313
2312.475834348744
2311.7196433567497
2311.2113464217964
2310.507022489415
2309.670428263189


In [30]:
print("After training: ")
print("Wh: ", wh)
print("\nWo: ", wo)

After training: 
Wh:  [[0.69957487 0.87512666 0.41239974 ... 0.84575312 0.79891813 0.46467346]
 [0.67562446 0.08355317 0.34516529 ... 0.50209053 0.6050203  0.09821812]
 [0.86067548 0.88360615 0.78410513 ... 0.91986775 0.34272435 0.75542436]
 ...
 [0.8769184  0.39586111 0.19199153 ... 0.81171451 0.59153932 0.28803569]
 [0.56190086 0.99803424 0.88875108 ... 0.85976545 0.09689954 0.45419041]
 [0.23997022 0.15165173 0.50661745 ... 0.6659217  0.06795409 0.34028176]]

Wo:  [[ 6.07745793e-01]
 [-2.77914224e-02]
 [ 1.34821094e-01]
 [ 5.69569243e-01]
 [ 3.92103519e-01]
 [ 5.23309768e-01]
 [ 1.66039491e-01]
 [ 4.18536610e-01]
 [ 3.13707762e-01]
 [ 8.02867724e-01]
 [ 3.91601582e-01]
 [ 3.18358118e-01]
 [ 3.33259144e-01]
 [ 6.91958984e-01]
 [ 7.64775480e-01]
 [ 5.44693196e-01]
 [ 6.19892543e-01]
 [ 6.85252407e-02]
 [ 7.48626363e-02]
 [ 3.48840796e-01]
 [ 7.94672398e-01]
 [ 8.70414216e-01]
 [ 7.21276903e-01]
 [ 5.51718623e-01]
 [ 3.99698982e-01]
 [ 4.47562891e-01]
 [ 5.78445713e-01]
 [ 1.93474653e-

In [31]:
zh = np.dot(test_X[1556], wh)
ah = sigmoid(zh)
zo = np.dot(ah, wo)
ao = sigmoid(zo)
print('predicted value: ',ao)
print('true value: ', test_Y[1556])
if ao>0.5:
    print("It's belong to class 1")
else:
    print("It's belong to class 0")

predicted value:  [0.5]
true value:  [0]
It's belong to class 0


In [32]:
#Function to predict test data with a forward pass
#If 'prediction > 0.5' then it belongs to class'1' otherwise class'0'

def prediction(test_set):
    
    predicted_class = np.zeros(test_set.shape[0], dtype = test_set.dtype)
    
    for i in range(len(test_set)):
        zh = np.dot(test_set[i], wh)
        ah = sigmoid(zh)
        zo = np.dot(ah, wo)
        ao = sigmoid(zo)
        
        if ao > 0.5:
            predicted_class[i] =  1
        else:
            predicted_class[i] = 0
        
    return predicted_class
           

In [33]:
predicted_test = prediction(test_X)

<ipython-input-28-34802458da0f>:4: RuntimeWarning: overflow encountered in exp
  return 1/(1 + np.exp(-x))


In [34]:
predicted_test

array([1., 0., 1., ..., 1., 1., 0.], dtype=float32)

In [35]:
predicted_test.shape

(2000,)

In [36]:
#printing the accuracy 
from sklearn.metrics import accuracy_score
ac = accuracy_score(test_Y,predicted_test)
print('Accuracy is: ', ac )

Accuracy is:  0.321
